use_frameworks!

platform :ios, '11.0'

target 'IJKMediaFramework_Example' do
  pod 'IJKMediaFramework', :path => '../'

  target 'IJKMediaFramework_Tests' do
    inherit! :search_paths

    
  end
end
